# stage 1: build
FROM node:16.20.1 as build

WORKDIR /app

COPY package.json yarn.lock /app/

RUN yarn install

COPY . /app

RUN ["yarn", "run", "build"]

# stage 2
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 3000

CMD [ "nginx", "-g", "daemon off;" ]
